dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run manage.py test --omit venv --settings=rbp_controller.settings.testing

after_success:
  - coveralls
