# Generated by Django 2.2.4 on 2019-09-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_devices.controller_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_devices.device_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AddressableLedStrip',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Device')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='LedStrip',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Device')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='PiGPIO',
            fields=[
                ('controller_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Controller')),
                ('hostname', models.CharField(max_length=50)),
                ('port', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'PiGPIO',
                'verbose_name_plural': 'PiGPIOs',
            },
            bases=('devices.controller',),
        ),
        migrations.CreateModel(
            name='RemoteSocket',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Device')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='WS2801AddressableLedStrip',
            fields=[
                ('addressableledstrip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.AddressableLedStrip')),
                ('total_led_count', models.PositiveIntegerField()),
                ('usable_led_count', models.PositiveIntegerField()),
                ('spi_channel', models.PositiveIntegerField()),
                ('spi_frequency', models.PositiveIntegerField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.PiGPIO')),
            ],
            options={
                'verbose_name': 'WS2801 Addressable Led Strip',
                'verbose_name_plural': 'WS2801 Addressable Led Strips',
            },
            bases=('devices.addressableledstrip',),
        ),
        migrations.CreateModel(
            name='RGBLedStrip',
            fields=[
                ('ledstrip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.LedStrip')),
                ('red_pin', models.PositiveIntegerField()),
                ('green_pin', models.PositiveIntegerField()),
                ('blue_pin', models.PositiveIntegerField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.PiGPIO')),
            ],
            options={
                'verbose_name': 'RGB Led Strip',
                'verbose_name_plural': 'RGB Led Strips',
            },
            bases=('devices.ledstrip',),
        ),
        migrations.CreateModel(
            name='ErloRemoteSocket',
            fields=[
                ('remotesocket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.RemoteSocket')),
                ('transmitter_pin', models.PositiveIntegerField()),
                ('group_code', models.CharField(max_length=50)),
                ('device_code', models.CharField(max_length=50)),
                ('repeats', models.PositiveIntegerField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.PiGPIO')),
            ],
            options={
                'verbose_name': 'Erlo Remote Socket',
                'verbose_name_plural': 'Erlo Remote Sockets',
            },
            bases=('devices.remotesocket',),
        ),
    ]
