# Generated by Django 2.2.4 on 2019-09-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonoffRemoteSocket',
            fields=[
                ('remotesocket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.RemoteSocket')),
                ('ip', models.CharField(max_length=50)),
                ('port', models.PositiveIntegerField()),
                ('device_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sonoff Remote Socket',
                'verbose_name_plural': 'Sonoff Remote Sockets',
            },
            bases=('devices.remotesocket',),
        ),
    ]
