# Generated by Django 2.2.2 on 2019-08-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteGPIOController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('controller_type', models.CharField(choices=[('PI', 'PIGPIO Controller'), ('AR', 'Arduino Controller'), ('FA', 'Fake Controller')], default='PI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('retries', models.IntegerField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_controller_api.RemoteGPIOController')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteSocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_controller_api.Transmitter')),
            ],
        ),
        migrations.CreateModel(
            name='LEDStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('red_pin', models.IntegerField()),
                ('green_pin', models.IntegerField()),
                ('blue_pin', models.IntegerField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_controller_api.RemoteGPIOController')),
            ],
        ),
        migrations.CreateModel(
            name='AddressableLEDStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('spi_device', models.IntegerField()),
                ('led_count', models.IntegerField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_controller_api.RemoteGPIOController')),
            ],
        ),
    ]
