# Generated by Django 2.2.2 on 2019-07-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitter',
            name='retries',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
