# Generated by Django 2.2.6 on 2019-10-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20191008_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
