# Generated by Django 2.2.6 on 2019-10-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_remove_action_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disableremotesocketaction',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='disableremotesocketaction',
            name='device',
        ),
        migrations.RemoveField(
            model_name='enableremotesocketaction',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='enableremotesocketaction',
            name='device',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='setledstripcoloraction',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='setledstripcoloraction',
            name='device',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='DisableRemoteSocketAction',
        ),
        migrations.DeleteModel(
            name='EnableRemoteSocketAction',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
        migrations.DeleteModel(
            name='SetLedStripColorAction',
        ),
    ]
